---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "minio-vault.serviceAccountName" . }}-kes-vault-auth
  labels:
    {{- include "minio-vault.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "minio-vault.serviceAccountName" . }}-kes-vault-auth
  labels:
    {{- include "minio-vault.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "minio-vault.serviceAccountName" . }}-kes-vault-auth
