apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "minio-vault.fullname" . }}-minio
  labels:
    {{- include "minio-vault.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "minio-vault.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "minio-vault.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "minio-vault.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: quay.io/minio/minio:RELEASE.2023-03-22T06-36-24Z
          imagePullPolicy: IfNotPresent
          command: ["minio", "server", "/data", "--console-address", ":9090"]
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: {{ include "minio-vault.fullname" . }}-minio
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: {{ include "minio-vault.fullname" . }}-minio
          ports:
            - name: http
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: http
          readinessProbe:
            httpGet:
              path: /minio/health/cluster/read
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "minio-vault.fullname" . }}-minio-data
              mountPath: /data
            - name: {{ include "minio-vault.fullname" . }}-minio-cert
              mountPath: /certs
      volumes:
        - name: {{ include "minio-vault.fullname" . }}-minio-data
          emptyDir:
            medium: Memory
        - name: {{ include "minio-vault.fullname" . }}-minio-cert
          secret:
            secretName: {{ include "minio-vault.fullname" . }}-minio-cert
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
