---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio-vault.fullname" . }}-minio
  labels:
    {{- include "minio-vault.labels" . | nindent 4 }}
data:
  accessKey: {{ .Values.minio.root.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.root.secretKey | b64enc | quote }}
