---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio-vault.fullname" . }}
  labels:
    {{- include "minio-vault.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9090
      targetPort: console
      protocol: TCP
      name: console
  selector:
    {{- include "minio-vault.selectorLabels" . | nindent 4 }}
