---
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kind
nodes:
  - role: control-plane
    image: kindest/node:v1.27.1
  - role: worker
    image: kindest/node:v1.27.1
  - role: worker
    image: kindest/node:v1.27.1
networking:
  apiServerPort: 6443
